### ISSUE TITLE
Version of unbound does not support "remote control"

### ISSUE THREAD

**Issue by gearhead** [cyclaero/void-zones-tools#4]
This is great! Got it going on my FreeNAS server. I would like a web interface similar to Pi-Hole and am trying to get netdata to work with it. I installed it as a package. When I try to add the remote terms for netdata in the unbound config, I get errors and unbound cannot read the config file.:
```
# This file was generated by local-unbound-setup.
# Modifications will be overwritten.
server:
        username: unbound
        interface: 0.0.0.0
        interface: ::0
        access-control: 192.168.2.0/24 allow
        access-control: 2001:db8:dead:beef::/48 allow
        directory: /var/unbound
        chroot: /var/unbound
        pidfile: /var/run/local_unbound.pid
        auto-trust-anchor-file: /var/unbound/root.key

remote-control:
      control-enable: yes
      control-interface: 127.0.0.1
      control-port: 8953

include: /var/unbound/local-void.zones
include: /var/unbound/forward.conf
include: /var/unbound/lan-zones.conf
include: /var/unbound/control.conf
include: /var/unbound/conf.d/*.conf
```
This results in a config file error:
```
# local-unbound-checkconf
/var/unbound/local-void.zones:1: error: syntax error
read /var/unbound/unbound.conf failed: 1 errors in configuration file
# service local_unbound restart
Stopping local_unbound.
Waiting for PIDS: 94565.
Starting local_unbound.
/var/unbound/local-void.zones:1: error: syntax error
read /var/unbound/unbound.conf failed: 1 errors in configuration file
[1595278533] local-unbound[97947:0] fatal error: Could not read config file: /var/unbound/unbound.conf. Maybe try unbound -dd, it stays on the commandline to see more errors, or unbound-checkconf
/etc/rc.d/local_unbound: WARNING: failed to start local_unbound
```
If I delete the 4 lines it loads and runs. Can I install the regular unbound package over this package and configure it that way?
